# Generated by Django 6.1.1 on 2026-09-19 12:24

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("entries", "0004_entryimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("manual", "chosen by hand"),
                            ("label", "everything with a label"),
                        ],
                        default="manual",
                        max_length=10,
                        verbose_name="kind",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="changed at"),
                ),
                (
                    "label",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="entries.tag",
                        verbose_name="label",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "collection",
                "verbose_name_plural": "collections",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CollectionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="added at"),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="collections.collection",
                        verbose_name="collection",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_memberships",
                        to="entries.entry",
                        verbose_name="entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "collection entry",
                "verbose_name_plural": "collection entries",
                "ordering": ("-added_at", "-pk"),
            },
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                models.F("owner"),
                django.db.models.functions.text.Lower("name"),
                name="unique_collection_per_owner_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "label"), ("label__isnull", False)),
                    models.Q(("kind", "manual"), ("label__isnull", True)),
                    _connector="OR",
                ),
                name="label_set_exactly_when_kind_is_label",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentry",
            constraint=models.UniqueConstraint(
                fields=("collection", "entry"), name="unique_entry_per_collection"
            ),
        ),
    ]
