# Generated by Django 6.1.1 on 2026-09-19 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "0001_initial"),
        ("entries", "0004_entryimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="secret",
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="show_images",
            field=models.BooleanField(default=False, verbose_name="show pictures"),
        ),
        migrations.AddField(
            model_name="collection",
            name="show_notes",
            field=models.BooleanField(default=False, verbose_name="show notes"),
        ),
        migrations.AddField(
            model_name="collection",
            name="show_tags",
            field=models.BooleanField(default=False, verbose_name="show labels"),
        ),
        migrations.AddField(
            model_name="collection",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, verbose_name="address"),
        ),
        migrations.AddField(
            model_name="collection",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("unlisted", "Anyone with the link"),
                    ("public", "Public"),
                ],
                default="private",
                max_length=10,
                verbose_name="visibility",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="visible_fields",
            field=models.ManyToManyField(
                blank=True,
                related_name="collections",
                to="entries.fielddefinition",
                verbose_name="visible fields",
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug", ""), _negated=True),
                fields=("owner", "slug"),
                name="unique_public_slug_per_owner",
            ),
        ),
    ]
