# Generated by Django 6.1.1 on 2026-09-10 23:03

from django.db import migrations, models

import hrcek.accounts.validators


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_apitoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[hrcek.accounts.validators.validate_domain],
                        verbose_name="domain",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="note"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="added at"),
                ),
            ],
            options={
                "verbose_name": "allowed domain",
                "verbose_name_plural": "allowed domains",
                "ordering": ("domain",),
            },
        ),
        migrations.CreateModel(
            name="AllowedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="note"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="added at"),
                ),
            ],
            options={
                "verbose_name": "allowed email address",
                "verbose_name_plural": "allowed email addresses",
                "ordering": ("email",),
            },
        ),
    ]
