# Generated by Django 6.1.1 on 2026-09-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="pending email address",
            ),
        ),
    ]
