# Generated by Django 6.1.1 on 2026-09-19 12:35

import django.db.models.functions.text
from django.db import migrations, models

import hrcek.accounts.validators


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_pending_email"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="namespace",
            field=models.CharField(
                blank=True,
                help_text="Only needed if you make a collection public. It appears in the address of every public collection you have, like /u/your-name/watches/.",
                max_length=50,
                null=True,
                validators=[hrcek.accounts.validators.validate_namespace],
                verbose_name="public name",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("namespace"),
                name="user_namespace_ci_unique",
            ),
        ),
    ]
