# Generated by Django 6.1.1 on 2026-09-13 12:03

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "text"),
                            ("number", "number"),
                            ("choice", "choice"),
                        ],
                        default="text",
                        max_length=10,
                        verbose_name="kind",
                    ),
                ),
                (
                    "options",
                    models.JSONField(blank=True, default=list, verbose_name="options"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_definitions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "field",
                "verbose_name_plural": "fields",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="FieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_text", models.TextField(blank=True, verbose_name="text value")),
                (
                    "value_number",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=20,
                        null=True,
                        verbose_name="number value",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="entries.fielddefinition",
                        verbose_name="field",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_values",
                        to="entries.entry",
                        verbose_name="entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "field value",
                "verbose_name_plural": "field values",
                "ordering": ("definition__name",),
            },
        ),
        migrations.AddConstraint(
            model_name="fielddefinition",
            constraint=models.UniqueConstraint(
                models.F("owner"),
                django.db.models.functions.text.Lower("name"),
                name="unique_field_per_owner_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldvalue",
            constraint=models.UniqueConstraint(
                fields=("entry", "definition"), name="unique_value_per_field_per_entry"
            ),
        ),
    ]
