# Generated by Django 6.1.1 on 2026-09-16 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0003_seed_default_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original", models.BinaryField(verbose_name="original")),
                (
                    "original_content_type",
                    models.CharField(max_length=60, verbose_name="original type"),
                ),
                ("display", models.BinaryField(verbose_name="display copy")),
                ("width", models.PositiveIntegerField(verbose_name="width")),
                ("height", models.PositiveIntegerField(verbose_name="height")),
                ("checksum", models.CharField(max_length=64, verbose_name="checksum")),
                (
                    "byte_size",
                    models.PositiveIntegerField(verbose_name="size in bytes"),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, max_length=2000, verbose_name="source address"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="added at"),
                ),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="entries.entry",
                        verbose_name="entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "image",
                "verbose_name_plural": "images",
            },
        ),
    ]
